CREATE DATABASE dbsprint;
USE dbsprint;

CREATE TABLE empresa(
idEmpresa INT PRIMARY KEY AUTO_INCREMENT,
nomeDaEmpresa VARCHAR(40) NOT NULL,
cnpjEmpresa VARCHAR(25) UNIQUE,
cep VARCHAR(9)
);

CREATE TABLE usuario (
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(40) NOT NULL,
email VARCHAR(70) UNIQUE,
senha VARCHAR(30) NOT NULL,
cpfUsuario VARCHAR(20) UNIQUE);

CREATE TABLE baseAlimentos(
idAlimentos INT PRIMARY KEY AUTO_INCREMENT,
nomeAlimento VARCHAR(40) UNIQUE,
temp DECIMAL(4,2) NOT NULL
);

CREATE TABLE dadosExtraidos (
idDados INT PRIMARY KEY AUTO_INCREMENT,
temperatura DECIMAL(4, 2) NOT NULL,
tempo DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE alertas(
idAlertas INT PRIMARY KEY AUTO_INCREMENT,
tempAlerta DECIMAL(5, 2) NOT NULL,
tempoAlerta DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);
